# Generated by Django 5.0.4 on 2024-05-03 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='uf',
        ),
    ]
